{% set name = "cfmask" %}
{% set version = "2.0.2" %}
{% set sha256 = "803441ac1467f36d920b8e87a04329d458e89f7cc3d3bc2f93e9abcdddefc1d0" %}

package:
    name: {{ name }}
    version: {{ version }}
    sha256: {{ sha256 }}

source:
    fn: {{ name }}-v{{ version }}.tar.gz
    url: https://github.com/USGS-EROS/espa-cloud-masking/archive/{{ name }}-v{{ version }}.tar.gz
    patches:
        - paths.patch

build:
    number: 0

requirements:
    build:
        - espa-product-formatter
    run:
        - espa-product-formatter

test:
    commands:
        - test -f $PREFIX/bin/cfmask

about:
    home: https://github.com/USGS-EROS/espa-cloud-masking
    license: NASA-1.3
    license_file: cfmask/CFMASK-LICENSE.txt
    summary: "Cloud detection and masking in Landsat imagery"

extra:
    recipe-maintainers:
        - yannforget
